export const phoneNumberRegex: RegExp = /[^0-9]/g
export const validateOnlyNumbers: RegExp = /^\d+$/
export const validateNumericOnly: RegExp = /[^0-9]/g
export const panNoRegex: RegExp = /[A-Z]{5}[0-9]{4}[A-Z]{1}/
export const gstRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z][Z][0-9A-Z]$/
export const panRegex = /^[A-Z]{5}[0-9]{4}[A-Z]$/
export const camelCaseRegex: RegExp = /([-_][a-z])/g
export const kebabCaseRegex: RegExp = /([a-z])([A-Z])/g
export const snakeCaseRegex: RegExp = /([a-z])([A-Z])/g
export const titleCaseRegex: RegExp = /\b\w/g
export const removeUnderscoreOrHyphenRegex: RegExp = /[_-]/g
export const hyphenRegex: RegExp = /-/g
export const underscoreRegex: RegExp = /_/g
export const camelCaseToWords = /([a-z])([A-Z])/g // Matches camelCase boundaries
export const digitsWithSpaces = /(\d+)/g // Matches digits to add spaces
export const multipleSpaces = /\s+/g // Matches multiple spaces
export const lowercaseFirstLetter = /\b[a-z]/g // Matches the first lowercase letter
