// Login
export const REQUEST_LOGIN: string = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS: string = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE: string = 'LOGIN_FAILURE'

export const REQUEST_SIGNUP: string = 'REQUEST_SIGNUP'
export const SIGNUP_SUCCESS: string = 'SIGNUP_SUCCESS'

export const VERIFY_OTP: string = 'VERIFY_OTP'
export const VERIFY_OTP_SUCCESS: string = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAILURE: string = 'VERIFY_OTP_FAILURE'

export const LOGOUT: string = 'LOGOUT'
export const LOGOUT_SUCCESS: string = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE: string = 'LOGOUT_FAILURE'

export const RESEND_OTP: string = 'RESEND_OTP'
export const RESEND_OTP_SUCCESS: string = 'RESEND_OTP_SUCCESS'
export const FORGOT_PASSWORD_FAILURE: string = 'FORGOT_PASSWORD_FAILURE'

export const FORGOT_PASSWORD: string = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS: string = 'FORGOT_PASSWORD_SUCCESS'

// User Requests
export const GET_USER_REQUESTS: string = 'GET_USER_REQUESTS'
export const GET_USER_REQUESTS_SUCCESS: string = 'GET_USER_REQUESTS_SUCCESS'

export const GET_CURRENT_USER_DATA: string = 'GET_CURRENT_USER_DATA'
export const GET_CURRENT_USER_DATA_SUCCESS: string =
  'GET_CURRENT_USER_DATA_SUCCESS'
export const GET_USER_REQUESTS_FAILURE: string = 'GET_USER_REQUESTS_FAILURE'

export const MANAGE_USER_ACCESS: string = 'MANAGE_USER_ACCESS'
export const MANAGE_USER_ACCESS_SUCCESS: string = 'MANAGE_USER_ACCESS_SUCCESS'
export const GET_SELECTED_USER_DATA: string = 'GET_SELECTED_USER_DATA'

export const SET_CURRENT_USER_STATUS: string = 'SET_CURRENT_USER_STATUS'
export const UPDATE_USER_DATA: string = 'UPDATE_USER_DATA'
export const UPDATE_USER_DATA_SUCCESS: string = 'UPDATE_USER_DATA_SUCCESS'

export const FLIGHT_SEARCH_REQUEST: string = 'FLIGHT_SEARCH_REQUEST'
export const FLIGHT_SEARCH_SUCCESS: string = 'FLIGHT_SEARCH_SUCCESS'
export const SAVE_FLIGHT_SEARCH_DATA: string = 'SAVE_FLIGHT_SEARCH_DATA'
export const GET_ALL_FLIGHT_LISTING_DATA: string = 'GET_ALL_FLIGHT_LISTING_DATA'

export const ADD_COUPON_DETAILS: string = 'ADD_COUPON_DETAILS'
export const ADD_COUPON_DETAILS_SUCCESS: string = 'ADD_COUPON_DETAILS_SUCCESS'

export const GET_BOOKING_DETAILS_DATA: string = 'GET_BOOKING_DETAILS_DATA'
export const GET_BOOKING_DETAILS_DATA_SUCCESS: string =
  'GET_BOOKING_DETAILS_DATA_SUCCESS'

export const GET_MY_BOOKING_DETAILS_DATA: string = 'GET_MY_BOOKING_DETAILS_DATA'
export const GET_MY_BOOKING_DETAILS_DATA_SUCCESS: string =
  'GET_MY_BOOKING_DETAILS_DATA_SUCCESS'

export const GET_COUPON_DETAILS: string = 'GET_COUPON_DETAILS'
export const GET_COUPON_DETAILS_SUCCESS: string = 'GET_COUPON_DETAILS_SUCCESS'
export const GET_COUPON_DETAILS_FAILURE: string = 'GET_COUPON_DETAILS_FAILURE'

export const ADD_MARKUP_DETAILS: string = 'ADD_MARKUP_DETAILS'
export const ADD_MARKUP_DETAILS_SUCCESS: string = 'ADD_MARKUP_DETAILS_SUCCESS'
export const GET_MARKUP_DETAILS: string = 'GET_MARKUP_DETAILS'
export const GET_MARKUP_DETAILS_SUCCESS: string = 'GET_MARKUP_DETAILS_SUCCESS'
export const GET_MARKUP_DETAILS_FAILURE: string = 'GET_MARKUP_DETAILS_FAILURE'

export const ADD_BALANCE: string = 'ADD_BALANCE'
export const ADD_BALANCE_SUCCESS: string = 'ADD_BALANCE_SUCCESS'
export const GET_BALANCE: string = 'GET_BALANCE'
export const GET_BALANCE_SUCCESS: string = 'GET_BALANCE_SUCCESS'
export const GET_BALANCE_FAILURE: string = 'GET_BALANCE_FAILURE'
