declare module "airlinedata" {
    export type SvgFileName =
        | "2GO (cargo airline)"
        | "ABX Air"
        | "ACES Colombia"
        | "ADC Airlines"
        | "AMC Airlines"
        | "AOM French Airlines"
        | "ARINC"
        | "ASL Airlines Belgium"
        | "ASL Airlines France"
        | "ASL Airlines Ireland"
        | "ASL Airlines Spain"
        | "ASL Airlines Switzerland"
        | "ATA Airlines"
        | "ATA Brasil"
        | "AccessAir"
        | "Ada Air"
        | "Adria Airways"
        | "Aegean Airlines"
        | "Aer Arann"
        | "Aer Lingus"
        | "AerSale"
        | "AeroBratsk"
        | "AeroLogic"
        | "AeroSur"
        | "Aerogem Aviation"
        | "Aerolínea de Antioquia"
        | "Aerolíneas Argentinas"
        | "Aeromar Líneas Aéreas Dominicanas"
        | "Aeroméxico Connect"
        | "Aeroméxico"
        | "Aeropelican Air Services"
        | "Aeroperú"
        | "Aeropostal Alas de Venezuela"
        | "AgustaWestland"
        | "Aigle Azur"
        | "Air Algérie"
        | "Air Alsie"
        | "Air Anatolia"
        | "Air Arabia"
        | "Air Astana"
        | "Air Atlanta Icelandic"
        | "Air Austral"
        | "Air Bagan"
        | "Air Berlin"
        | "Air Bourbon"
        | "Air Busan"
        | "Air Calédonie"
        | "Air Canada Rouge"
        | "Air Canada"
        | "Air China"
        | "Air Choice One"
        | "Air Columbus"
        | "Air Corsica"
        | "Air Djibouti"
        | "Air Do"
        | "Air Dolomiti"
        | "Air Europa"
        | "Air Finland"
        | "Air Florida"
        | "Air France Hop"
        | "Air France"
        | "Air Gabon"
        | "Air Greenland"
        | "Air Haïti"
        | "Air Holland"
        | "Air Hong Kong"
        | "Air India Express"
        | "Air India"
        | "Air Inuit"
        | "Air Italy"
        | "Air Jamaica"
        | "Air Luxor"
        | "Air Macau"
        | "Air Madagascar"
        | "Air Madrid"
        | "Air Malawi"
        | "Air Malta"
        | "Air Mauritius"
        | "Air Memphis"
        | "Air Minas Linhas Aéreas"
        | "Air Moldova"
        | "Air Namibia"
        | "Air New Zealand"
        | "Air Niugini"
        | "Air North (4N)"
        | "Air Paradise International"
        | "Air Partner"
        | "Air Seoul"
        | "Air Serbia"
        | "Air Seychelles"
        | "Air Tahiti Nui"
        | "Air Transat (TS)"
        | "Air Vanuatu"
        | "Air Vegas"
        | "Air Zimbabwe"
        | "AirAsia India"
        | "AirAsia X"
        | "AirAsia Zest"
        | "AirAsia"
        | "AirBaltic"
        | "AirBridgeCargo"
        | "AirTran Airways"
        | "Airblue"
        | "Airborne Express"
        | "Airbus A330"
        | "Airbus Defence and Space"
        | "Airbus Helicopters"
        | "Airbus"
        | "Aircalin"
        | "Airlines of Tasmania"
        | "Airlink"
        | "Airnorth"
        | "Airpink"
        | "Airservices Australia"
        | "Aklak Air"
        | "Alaska Airlines"
        | "Albanian Airlines"
        | "Albatros Airways"
        | "Albawings"
        | "Alitalia"
        | "All Nippon Airways"
        | "Allegiant Air"
        | "Alliance Airlines"
        | "Alliant Techsystems"
        | "Aloha Airlines"
        | "America West Airlines"
        | "American Airlines"
        | "Ameriflight"
        | "Ansett Australia"
        | "Antonov"
        | "Ariana Afghan Airlines"
        | "Ariana afghan"
        | "Arik Air"
        | "Arkia"
        | "Armavia"
        | "Armenia"
        | "Aserca Airlines"
        | "Asiana Airlines"
        | "Astra Airlines"
        | "Atlantic Airways"
        | "Atlantic Coast Airlines"
        | "Atlantic Southeast Airlines"
        | "Atlas Air"
        | "Atlas Blue"
        | "AtlasGlobal"
        | "Aurela"
        | "Aurigny"
        | "Australian airExpress"
        | "Avation"
        | "Avelo (XP)"
        | "Avensa"
        | "Aviacsa"
        | "Avianca Argentina"
        | "Avianca Brasil S.A."
        | "Avianca Costa Rica"
        | "Avianca Ecuador"
        | "Avianca El Salvador"
        | "Avianca"
        | "Aviance UK"
        | "Aviateca"
        | "Avies"
        | "Avior Airlines"
        | "Azerbaijan Airlines"
        | "Azores Airlines"
        | "Azul Brazilian Airlines"
        | "Azzurra Air"
        | "BA Connect"
        | "BAE Systems Australia"
        | "BAE Systems"
        | "BAX Global"
        | "BIOVIA"
        | "BRA Transportes Aéreos"
        | "Babcock Mission Critical Services Offshore"
        | "Babcock Mission Critical Services Onshore"
        | "Bangkok Airways"
        | "Beechcraft"
        | "Belgian Air Component"
        | "Belle Air Europe"
        | "Belle Air"
        | "Bergen Air Transport"
        | "Beta Technologies"
        | "Bharat Electronics Limited"
        | "Biman Bangladesh Airlines"
        | "Binter Canarias"
        | "Blue Air  (1)"
        | "Blue Air"
        | "Blue Origin"
        | "Blue Panorama Airlines"
        | "Blue Wings"
        | "Boeing Australia"
        | "Boeing Canada"
        | "Boeing Capital"
        | "Boeing Commercial Airplanes"
        | "Boeing Defense, Space & Security"
        | "Boeing NeXt"
        | "Boeing Rotorcraft Systems"
        | "Boeing"
        | "Boliviana de Aviación"
        | "Bombardier Aviation"
        | "Bombardier Inc."
        | "Boom Technology"
        | "Bouraq Indonesia Airlines"
        | "Breeze Airways (MX)"
        | "Bristow Helicopters"
        | "Bristow Norway"
        | "British Aircraft Corporation"
        | "British Airways"
        | "British Regional Airlines"
        | "Brussels Airlines"
        | "Buddha Air"
        | "Bulgaria Air"
        | "CAE Inc."
        | "CAL Cargo Air Lines"
        | "CASA (aircraft manufacturer)"
        | "CFM International"
        | "CHC Helicopter"
        | "Calm Air"
        | "CanJet"
        | "Canadian Airlines"
        | "Canadian North"
        | "Canadian Pacific Air Lines"
        | "Cape Air"
        | "Cargojet (W8)"
        | "Cargojet"
        | "Cargolux"
        | "Carpatair"
        | "Cathay Dragon"
        | "Cathay Pacific"
        | "Cayman Airways"
        | "Cebgo"
        | "Cebu Pacific"
        | "Centralwings"
        | "Cessna"
        | "Cham Wings"
        | "Chemring Group"
        | "China Eastern Airlines"
        | "China National Aviation Corporation"
        | "China Southern Airlines"
        | "Cirrus Airlines"
        | "CityJet"
        | "Civil Aviation Authority (United Kingdom)"
        | "Civil Aviation Authority of New Zealand"
        | "Cobalt Air"
        | "Cobham Aviation Services Australia"
        | "Cobham plc"
        | "Collins Aerospace"
        | "Comac"
        | "Comair (South Africa)"
        | "Comair"
        | "Condor Flugdienst GmbH"
        | "Contact Air"
        | "Continental Airlines"
        | "Copa Airlines"
        | "Corendon Airlines  (1)"
        | "Corendon Airlines"
        | "Corendon Dutch Airlines"
        | "Croatia Airlines"
        | "Cubana de Aviación"
        | "Curtiss Aeroplane and Motor Company"
        | "Czech Air Force"
        | "Czech Airlines"
        | "DASA"
        | "DHL Aviation"
        | "DSPACE GmbH"
        | "Danish Air Transport"
        | "Darwin Airline"
        | "Dassault Aviation"
        | "Dauair"
        | "Delta Air Lines"
        | "Diamond Aircraft Industries"
        | "Do & Co"
        | "DutchBird"
        | "Eastar Jet"
        | "Eastern Air Lines (2015)"
        | "Eastern Air Lines"
        | "Eastern Airlines (2D)"
        | "Eastern Airways"
        | "EasyJet"
        | "EgyptAir"
        | "Egyptian Air Force"
        | "El Al Israel"
        | "El Al"
        | "Embraer"
        | "Embry–Riddle Aeronautical University"
        | "Emerald Airways"
        | "Emirates (airline)"
        | "Endeavor Air"
        | "Engine Alliance"
        | "Envoy Air"
        | "Erickson Inc."
        | "Esterline"
        | "Estonian Air"
        | "Ethiopian Airlines"
        | "Etihad Airways (EY)"
        | "Eurocontrol"
        | "Eurofly"
        | "Eurolot"
        | "European Air Express"
        | "Eurowings Europe"
        | "Eurowings"
        | "Evergreen International Airlines"
        | "FedEx Express"
        | "Fiji Airways"
        | "Finnair"
        | "Finnish Air Force"
        | "Firefly (airline)"
        | "First Air"
        | "Fischer Air"
        | "Flair Airlines"
        | "FlightAware"
        | "Flightradar24"
        | "Fly Baghdad"
        | "Fly Iraqi"
        | "Fly Persia"
        | "Fly Pro"
        | "FlyNordic"
        | "Flybe"
        | "Flybmi"
        | "Flydubai"
        | "Flynas"
        | "Flyr AS (FS)"
        | "Focke Wulf"
        | "Ford Aerospace"
        | "Four Star Air Cargo"
        | "Frontier (F9)"
        | "GB Airways"
        | "GE Capital Aviation Services"
        | "GE Technology Infrastructure"
        | "GKN"
        | "Garuda Indonesia"
        | "General Atomics"
        | "General Dynamics"
        | "German Aerospace Center"
        | "German Air Force"
        | "Germania (airline)"
        | "Germanwings"
        | "Gol Transportes Aéreos"
        | "Goodrich Corporation"
        | "Grand Canyon Airlines"
        | "Grumman"
        | "Grupo Aeroportuario Centro Norte"
        | "HK Express"
        | "Hahn Air"
        | "Hainan Airlines"
        | "Hamburg International"
        | "Handley Page"
        | "Hanwha Aerospace"
        | "Harris Corporation"
        | "Hawaiian Airlines"
        | "Hawker Beechcraft"
        | "HeavyLift Cargo Airlines"
        | "Heliswiss"
        | "Helvetic Airways"
        | "Hi Fly (airline)"
        | "Hi Fly Malta"
        | "Hokkaido Air System"
        | "Honeywell Aerospace"
        | "Hong Kong Airlines"
        | "Hughes Helicopters"
        | "Hungarian Air Force"
        | "Héroux Devtek"
        | "ICON Aircraft"
        | "INVAP"
        | "IZair"
        | "Iberia (airline)"
        | "Iberia Express"
        | "Icelandair"
        | "Independence Air"
        | "IndiGo"
        | "Insel Air"
        | "InterSky"
        | "International Airlines Group"
        | "Iran Air"
        | "Iraqi Airways"
        | "Irkut Corporation"
        | "Island Airlines"
        | "Isles of Scilly Skybus"
        | "Israir"
        | "ItAli Airlines"
        | "Ivchenko Progress"
        | "Japan Airlines Domestic"
        | "Japan Airlines"
        | "Japan Asia Airways"
        | "Japan Transocean Air"
        | "Jat Airways"
        | "Jazeera Airways  (1)"
        | "Jazeera Airways"
        | "Jeju Air"
        | "Jeppesen"
        | "Jet Airways"
        | "Jet Time"
        | "Jet2.com"
        | "Jet4you"
        | "JetBlue"
        | "Jetalliance"
        | "Jetstar Airways"
        | "Jetstar Asia Airways"
        | "Jetstar Hong Kong"
        | "Jetstar Japan"
        | "Jetstar Pacific"
        | "John C. Stennis Space Center"
        | "John Menzies"
        | "KLM"
        | "Kaman Corporation"
        | "Kawasaki Aerospace Company"
        | "Kenya Airways"
        | "Khrunichev State Research and Production Space Center"
        | "Korean Air"
        | "Kuwait Airways"
        | "L3 Technologies"
        | "L3Harris Technologies"
        | "LATAM Argentina"
        | "LATAM Brasil"
        | "LATAM Cargo Brasil"
        | "LATAM Cargo Chile"
        | "LATAM Chile"
        | "LATAM Colombia"
        | "LATAM Express"
        | "LATAM Paraguay"
        | "LOT Polish Airlines"
        | "LTU Austria"
        | "LTU International"
        | "La Compagnie"
        | "Lancair"
        | "Lauda Air"
        | "Leonardo S.p.A."
        | "Level (airline brand)"
        | "Lion Air"
        | "Lloyd Aéreo Boliviano"
        | "Lockheed Martin Aeronautics"
        | "Lockheed Martin"
        | "Loganair"
        | "Lufthansa Cargo"
        | "Lufthansa CityLine"
        | "Lufthansa"
        | "Luxair"
        | "Lycoming Engines"
        | "LyddAir"
        | "Línea Aérea Amaszonas"
        | "Líneas Aéreas Azteca"
        | "Líneas Aéreas Privadas Argentinas"
        | "Líneas Aéreas Suramericanas"
        | "MTU Aero Engines"
        | "Macedonian Airlines"
        | "Mahan Air"
        | "Malindo Air"
        | "Malév Hungarian Airlines"
        | "Mandarin Airlines"
        | "Mango (airline)"
        | "MarkAir"
        | "Martinair"
        | "McDonnell Douglas"
        | "Meggitt PLC"
        | "MenaJet"
        | "Messerschmitt"
        | "Mexicana de Aviación"
        | "Middle East Airlines"
        | "Midwest Airlines"
        | "Mihin Lanka"
        | "Moldavian Airlines"
        | "Monarch Airlines"
        | "Montenegro Airlines"
        | "Moog Inc."
        | "Motor Sich"
        | "Mu Space"
        | "Myanmar Airways International"
        | "NHIndustries"
        | "Nav Canada"
        | "Neos (airline)  (1)"
        | "Neos (airline)"
        | "Nextjet"
        | "Niki (airline)"
        | "Nippon Cargo Airlines"
        | "Nok Air"
        | "Nolinor Aviation"
        | "Nordwind Airlines"
        | "Norse Atlantic Airways (N0)"
        | "Northern Air Cargo"
        | "Northrop Grumman Innovation Systems"
        | "Northwest Airlines"
        | "Northwestern Air"
        | "Norwegian Air Norway AS (DH)"
        | "Norwegian Air Shuttle (DY)"
        | "Nouvelair"
        | "Novosibirsk Aircraft Production Association"
        | "OLT Express Germany"
        | "OLT Express"
        | "Olympic Air"
        | "Oman Air"
        | "Oneworld"
        | "Onur Air"
        | "OpenSkies"
        | "OzJet"
        | "PAL Express"
        | "Pan American Airways (1996–1998)"
        | "Pan American Airways (1998–2004)"
        | "Pan American World Airways"
        | "Paranair"
        | "Passaredo Linhas Aéreas"
        | "Patria (company)"
        | "Pegasus Airlines"
        | "Pel Air"
        | "People's"
        | "Perimeter Aviation"
        | "Philippine Airlines"
        | "Philippines AirAsia"
        | "Piedmont Airlines"
        | "Piper Aircraft"
        | "Polar Air Cargo"
        | "Porter Airlines"
        | "Pouya air"
        | "Pratt & Whitney"
        | "Precision Air"
        | "Primaris Airlines"
        | "Primera Air"
        | "PrivatAir"
        | "Qantas"
        | "QantasLink"
        | "Qatar Airways"
        | "Qinetiq"
        | "Raven Industries"
        | "Raya Airways"
        | "Raytheon Technologies"
        | "Raytheon"
        | "Regional Express Airlines"
        | "Rich International Airways"
        | "Robinson Helicopter Company"
        | "Rockwell International"
        | "Rogožarski"
        | "Rolls Royce Controls and Data Services"
        | "Rolls Royce Holdings"
        | "Rolls Royce Limited"
        | "Royal Air Force of Oman"
        | "Royal Air Maroc"
        | "Royal Brunei Airlines"
        | "Royal Flying Doctor Service of Australia"
        | "Royal Jordanian"
        | "RwandAir"
        | "Ryanair"
        | "S7 Airlines"
        | "SAS Braathens"
        | "SATA Air Açores"
        | "SBA Airlines"
        | "SCAT Airlines"
        | "SIA Engineering Company"
        | "SNCASE"
        | "SNCASO"
        | "Safair"
        | "Salam Air"
        | "Saudi Arabian (SV)"
        | "Saudia"
        | "SaxonAir"
        | "Scandinavian Airlines"
        | "Scoot"
        | "Shandong Airlines"
        | "Shanghai Airlines"
        | "Sharp Airlines"
        | "Shenzhen Airlines"
        | "Shree Airlines"
        | "Sichuan Airlines"
        | "SilkAir"
        | "Singapore Airlines Cargo"
        | "Singapore Airlines"
        | "Sky Airlines"
        | "SkyTeam"
        | "SkyWest, Inc."
        | "SkyWork Airlines"
        | "Skybus Airlines"
        | "Skymark Airlines"
        | "Smartwings Hungary"
        | "Smartwings"
        | "Sol Linhas Aéreas"
        | "South African Airways"
        | "South African Express"
        | "Southern Airways"
        | "Southwest Airlines"
        | "Sozvezdie"
        | "SpaceX"
        | "Spanair"
        | "Spectrum Aeronautical"
        | "SpiceJet (SG)"
        | "Spirit Airlines"
        | "Spring Airlines"
        | "Spyker"
        | "SriLankan Airlines"
        | "Star Alliance"
        | "Starlink Aviation"
        | "Sterling Airlines"
        | "Sudan Airways"
        | "Sukhoi"
        | "Sun Country (SY)"
        | "SunExpress"
        | "Sunwing Airlines"
        | "SuperJet International"
        | "Surf Air"
        | "Swe Fly"
        | "Swift Air"
        | "Swiss Global Air Lines"
        | "Swiss International Air Lines"
        | "Swissair"
        | "T'way Air"
        | "TAP Air Portugal"
        | "TAR Aerolíneas"
        | "TAROM"
        | "TUI Airways"
        | "TUI fly Deutschland"
        | "TUI fly Netherlands"
        | "Techniques d'Avant Garde"
        | "Textron"
        | "Thai AirAsia X"
        | "Thai AirAsia"
        | "Thai Airways"
        | "Thai Smile"
        | "Thales Group"
        | "Thales Training & Simulation"
        | "The Aerospace Corporation"
        | "Tianjin Airlines"
        | "Tigerair Australia"
        | "Tigerair Mandala"
        | "Tigerair"
        | "Total Linhas Aéreas"
        | "Transaero"
        | "Transavia France"
        | "Transavia"
        | "Tunisair"
        | "Turkish Aerospace Industries"
        | "Turkish Air Force"
        | "Turkish Airlines"
        | "US Airways"
        | "USA3000 Airlines"
        | "UVT Aero"
        | "Ukraine International Airlines"
        | "United Aircraft Corporation"
        | "United Airlines Holdings"
        | "United Airlines"
        | "United Launch Alliance"
        | "Uzbekistan Airways"
        | "VASP"
        | "ValuJet Airlines"
        | "Vanilla Air"
        | "Vantage Airport Group"
        | "VietJet Air"
        | "Vietnam Air Services Company"
        | "Vietnam Airlines"
        | "Viking Air"
        | "Virgin America"
        | "Virgin Australia"
        | "Virgin Group"
        | "Vistara"
        | "Vladivostok Air"
        | "Volaris"
        | "Volga Dnepr Airlines"
        | "Volotea"
        | "Vueling  (1)"
        | "Vueling"
        | "Wamos Air"
        | "Wataniya Airways"
        | "Welcome Air"
        | "West Air Sweden"
        | "West Atlantic UK"
        | "West Wind Aviation"
        | "WestJet Encore"
        | "WestJet"
        | "Western Airlines"
        | "Widerøe"
        | "Winair"
        | "Wings Air"
        | "Wizz Air"
        | "World Airways"
        | "XL Airways Germany"
        | "XiamenAir"
        | "Yangon Airways"
        | "Yeti Airlines"
        | "Zip (airline)"
        | "Zodiac Aerospace"
}